//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncfusionVideosPortal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hackathon_Platform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hackathon_Platform()
        {
            this.Hackathon_Control = new HashSet<Hackathon_Control>();
            this.Hackathon_Videos = new HashSet<Hackathon_Videos>();
        }
    
        public int PlatformId { get; set; }
        public string PlatformName { get; set; }
        public string ShortName { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hackathon_Control> Hackathon_Control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hackathon_Videos> Hackathon_Videos { get; set; }
    }
}
